### ISSUE TITLE
Monterey support?

### ISSUE THREAD

**Issue by seathasky** [luchina-gabriel/BASE-EFI-INTEL-DESKTOP-4THGEN-HASWELL#1]
To start off. Thank you soo much for the clean EFI. It's been a headache to get this old OC updated past 0.6.6. I was able to finally get it updated to 0.7.5 by comparing my current efi to yours and by adding few things in your troubleshooting section.

I'm curious if it's possible to install Monterey on Haswell and if so do I need to change my smbios to iMacPro1,1 or can I keep the iMac15,1 I'm currently using now.

Thanks!

**Comment by luchina-gabriel** [comment]
Hey seathasky, what's up!?

Nice, thanks for your feedback, i'm happy :)

About support of Monterey, I recomend that you change your SMBIOS to iMacPro1,1 or MacPro7,1, both may work without any problems with OC version 0.7.4+.

Regards,
Gabriel

**Comment by seathasky** [comment]
Thanks! Got it working with 1.1, appreciate the assist!
